module gw_movmtn

!
! This module parameterizes gravity waves generated by the obstacle effect produced by
! internal circulations in the atmosphere.
!

use gw_utils, only: r8

implicit none
private
save

public :: MovMtnSourceDesc
public :: gw_movmtn_src

type :: MovMtnSourceDesc
   ! Whether wind speeds are shifted to be relative to storm cells.
   logical :: storm_shift
   ! Index for level where wind speed is used as the source speed.
   integer :: k
   ! Heating depths below this value [m] will be ignored.
   real(r8) :: min_hdepth
   ! Table bounds, for convenience. (Could be inferred from shape(mfcc).)
   integer :: maxh !-bounds of the lookup table heating depths
   integer :: maxuh ! bounds of the lookup table wind
   ! Heating depths [m].
   real(r8), allocatable :: hd(:), uh(:)
   ! Table of source spectra.
   real(r8), allocatable :: mfcc(:,:,:)  !is the lookup table f(depth, wind, phase speed)
end type MovMtnSourceDesc

contains

!==========================================================================

subroutine gw_movmtn_src(ncol,lchnk, band, desc, u, v, &
     netdt, netdt_shcu, xpwp_shcu, vorticity, &
     zm, pmid, delp, alpha_gw_movmtn, movmtn_source, ksteer_in, klaunch_in, &
     src_level, tend_level, tau, ubm, ubi, xv, yv, &
     c, hdepth, p_steer, p_launch, tilt, &
     k_steer_out, k_launch_out, &
     xpwp_src_1, xpwp_src_2, xpwp_src_3 )
!-----------------------------------------------------------------------
! Flexible driver for gravity wave source from obstacle effects produced
! by internal circulations
!-----------------------------------------------------------------------
  use gw_utils, only: get_unit_vector, dot_2d, midpoint_interp
  use gw_common, only: GWBand, pver, qbo_hdepth_scaling
  !use cam_history, only: outfld
  use phys_control,   only: use_gw_movmtn_pbl
  use physconst,      only: rair, gravit
!------------------------------Arguments--------------------------------
  ! Column dimension.
  integer, intent(in) :: ncol , lchnk

  ! Wavelengths triggered by convection.
  type(GWBand), intent(in) :: band

  ! Settings for convection type (e.g. deep vs shallow).
  type(MovMtnSourceDesc), intent(in) :: desc

  ! Midpoint zonal/meridional winds.
  real(r8), intent(in) :: u(ncol,pver), v(ncol,pver)
  ! Heating rate due to convection.
  real(r8), intent(in) :: netdt(:,:)  !from deep scheme
  ! Heating rate due to shallow convection and PBL turbulence.
  real(r8), intent(in) :: netdt_shcu(:,:)
  ! Higher order flux from ShCu/PBL.
  real(r8), intent(in) :: xpwp_shcu(ncol,pver+1)
  ! Relative vorticity
  real(r8), intent(in) :: vorticity(ncol,pver)
  ! Midpoint altitudes.
  real(r8), intent(in) :: zm(ncol,pver)
  ! Midpoint pressures.
  real(r8), intent(in) :: pmid(ncol,pver), delp(ncol,pver)
  ! tunable parameter controlling proportion of PBL momentum flux emitted as GW
  real(r8), intent(in) :: alpha_gw_movmtn
  ! code for source of gw: 1=vorticity, 2=upwp
  integer, intent(in) :: movmtn_source
  ! Steering level and launch level inputs
  integer, intent(in) :: ksteer_in, klaunch_in

  ! Indices of top gravity wave source level and lowest level where wind
  ! tendencies are allowed.
  integer, intent(out) :: src_level(ncol)
  integer, intent(out) :: tend_level(ncol)

  ! Wave Reynolds stress.
  real(r8), intent(out) :: tau(ncol,-band%ngwv:band%ngwv,pver+1) !tau = momentum flux (m2/s2) at interface level ngwv = band of phase speeds
  ! Projection of wind at midpoints and interfaces.
  real(r8), intent(out) :: ubm(ncol,pver), ubi(ncol,pver+1)
  ! Unit vectors of source wind (zonal and meridional components).
  real(r8), intent(out) :: xv(ncol), yv(ncol) !determined by vector direction of wind at source
  ! Phase speeds.
  real(r8), intent(out) :: c(ncol,-band%ngwv:band%ngwv)

  ! Heating depth [m] and maximum heating in each column.
  real(r8), intent(out) :: hdepth(ncol)    !calculated here in this code
  
  ! pressure of steering and launch leevels (Pa)
  real(r8), intent(out) :: p_steer(ncol) 
  real(r8), intent(out) :: p_launch(ncol)  
  ! indices of steering and launch leevels (Pa)
  real(r8), intent(out) :: k_steer_out(ncol) 
  real(r8), intent(out) :: k_launch_out(ncol)  
  ! Relative vorticity
  real(r8), intent(out) :: tilt(ncol,pver)
  ! Source momentum fluxes
  real(r8), intent(out) :: xpwp_src_1(ncol), xpwp_src_2(ncol), xpwp_src_3(ncol)

!---------------------------Local Storage-------------------------------
  ! Column and (vertical) level indices.
  integer :: i, k

  ! Zonal/meridional wind at steering level, i.e., 'cell speed'.
  ! May be later modified by retrograde motion ....
  real(r8) :: usteer(ncol), vsteer(ncol)
  real(r8) :: uwavef(ncol,pver),vwavef(ncol,pver)
  ! Steering , launch levels 
  real(r8) :: steer_level(ncol)
  integer  :: steer_level_indx(ncol)
  integer  :: launch_level_indx(ncol)
  ! Retrograde motion of Cell
  real(r8) :: Cell_Retro_Speed(ncol)

  ! Maximum heating rate.
  real(r8) :: q0(ncol), qj(ncol)
  ! unit vector components at steering level and mag
  real(r8) :: xv_steer(ncol), yv_steer(ncol), umag_steer(ncol)
  ! Bottom/top heating range index.
  integer  :: boti(ncol), topi(ncol)
  ! Index for looking up heating depth dimension in the table.
  integer  :: hd_idx(ncol)
  ! Mean wind in heating region.
  real(r8) :: uh(ncol)
  ! Min/max wavenumber for critical level filtering.
  integer :: Umini(ncol), Umaxi(ncol)
  ! Source level tau for a column.
  real(r8) :: tau0(-band%ngwv:band%ngwv)
  ! Speed of convective cells relative to storm.
  real(r8) :: CS(ncol),CS1(ncol)
  ! Wind speeds in wave direction
  real(r8) :: udiff(ncol),vdiff(ncol)
  ! "on-crest" source level wind
  real(r8) :: ubmsrc(ncol),ubisrc(ncol)

  ! Index to shift spectra relative to ground.
  integer :: shift
  ! Other wind quantities
  real(r8) :: ut(ncol),uc(ncol),umm(ncol)
  ! Tau from moving mountain lookup table
  real(r8) :: taumm(ncol)
  ! Heating rate conversion factor.  -> tuning factors
  real(r8), parameter :: CF = 20._r8  !(1/ (5%))  -> 5% of grid cell is covered with convection
  ! Averaging length.
  real(r8), parameter :: AL = 1.0e5_r8
  ! Index for moving mountain lookuptable
  integer :: hdmm_idx(ncol), uhmm_idx(ncol)
  ! Index for ground based phase speed bin
  real(r8) :: c0(ncol,-band%ngwv:band%ngwv)
  integer :: c_idx(ncol,-band%ngwv:band%ngwv)
  ! GW Flux source
  real(r8) :: xpwp_src(ncol)
  ! Manual steering level set
  integer :: Steer_k(ncol), Launch_k(ncol)
  ! Set source (1=vorticity, 2=PBL mom fluxes)
  integer :: source_type

  ! centroid search params
  real(r8) :: p_min_centroid, p_max_centroid

  ! scale factor for flow-dep tilt source
  real(r8) :: scale_factor_tilt_src
  
  !----------------------------------------------------------------------
  ! Initialize tau array
  !----------------------------------------------------------------------
  tau = 0.0_r8
  hdepth = 0.0_r8
  q0 = 0.0_r8
  tau0 = 0.0_r8
  xpwp_src_1 = 0.0_r8
  xpwp_src_2 = 0.0_r8
  xpwp_src_3 = 0.0_r8

  write(*,*) " Debugging gw_movmtn.F90 "
  write(*,*) " use_gw_movmtn_pbl" , use_gw_movmtn_pbl
  write(*,*) " movmtn_source    " , movmtn_source
  write(*,*) " min max vort     " ,  minval( vorticity ) , maxval( vorticity )

  !!!!!!!!!!!!!!!!!!!!!!!!!!!
  call compute_tilt(u, v, vorticity, zm, ncol, pver, tilt)

  source_type=3 !movmtn_source
  if ( source_type==1 ) then
     !----------------------------------------------------------------------
     ! Calculate flux source from vorticity
     !----------------------------------------------------------------------
     call vorticity_flux_src( vorticity, ncol, pver , alpha_gw_movmtn, xpwp_src, Steer_k, Launch_k )
     xpwp_src_1 = xpwp_src
  else if ( source_type==2 ) then
     !----------------------------------------------------------------------
     ! Calculate flux source from ShCu/PBL and set Steering level
     !----------------------------------------------------------------------
     call shcu_flux_src( xpwp_shcu, ncol, pver+1, alpha_gw_movmtn, xpwp_src, Steer_k, Launch_k )
     xpwp_src_2 = xpwp_src
  else if ( source_type==3 ) then
     !----------------------------------------------------------------------
     ! Calculate flux source from tilt w/ dynamic steer/launch
     !----------------------------------------------------------------------
     !call tilt_dyn_src( vorticity, u, v, zm, pmid, delp, ncol, pver+1, alpha_gw_movmtn, xpwp_src, Steer_k, Launch_k )
     call tilt_dyn_src(tilt, u, v, pmid, delp, ncol, pver, alpha_gw_movmtn, &
          xpwp_src, Steer_k, Launch_k, p_steer, p_launch, &
          usteer, vsteer)
     xpwp_src_3 = xpwp_src
  end if

  !-------------------------------------------------
  ! Override steering and launch levels if inputs>0
  !-------------------------------------------------
  if ( (klaunch_in > 0).and.(source_type /= 3) ) then
     Launch_k(:ncol) = klaunch_in
  end if
  if ( (ksteer_in > 0).and.(source_type /= 3 ) ) then
     Steer_k(:ncol) = ksteer_in
  end if

  !--------------------------------------------
  ! Fill output diags
  !-------------------------------------------
  k_steer_out  = Steer_k
  k_launch_out = Launch_k
  
  ! Get the unit vector components and magnitude at the steering level.
  call get_unit_vector(usteer, vsteer, xv_steer, yv_steer, umag_steer)

  !-------------------------------------------------------------------------
  ! If we want to account for some retorgrade cell motion,
  ! it should be done by vector subtraction from (usteer,vsteer).
  ! We assume the retrograde motion is in the same direction as
  ! (usteer,vsteer) or the unit vector (xv_steer,yv_steer). Then, the
  ! vector retrograde motion is just:
  !      = -Cell_Retrograde_Speed * (xv_steer,yv_steer)
  ! and we would modify usteer and vsteer
  !     usteer = usteer - Cell_Retrograde_Speed * xv_steer
  !     vsteer = vsteer - Cell_Retrograde_Speed * yv_steer
  !-----------------------------------------------------------------------
  ! Cell_Retro_Speed is always =0 for now
  !-----------------------------------------------------------------------
  do i=1,ncol
     Cell_Retro_Speed(i) = 0._r8 !min( sqrt(usteer(i)**2 + vsteer(i)**2), 0._r8)
  end do
  do i=1,ncol
     usteer(i) = usteer(i) - xv_steer(i)*Cell_Retro_Speed(i)
     vsteer(i) = vsteer(i) - yv_steer(i)*Cell_Retro_Speed(i)
  end do
  !-------------------------------------------------------------------------
  ! At this point (usteer,vsteer) is the cell-speed, or equivalently, the 2D
  ! ground based wave phase speed for moving mountain GW
  !-------------------------------------------------------------------------


  ! Calculate heating depth.
  !
  ! Heating depth is defined as the first height range from the bottom in
  ! which heating rate is continuously positive.
  !-----------------------------------------------------------------------

  ! First find the indices for the top and bottom of the heating range.
  !nedt is heating profile from Zhang McFarlane (it's pressure coordinates, therefore k=0 is the top)

  boti = 0 !bottom
  topi = 0  !top

  if (use_gw_movmtn_pbl) then
     boti=pver
     topi=Launch_k ! Launch levels for GW
  else
    do k = pver, 1, -1 !start at surface
       do i = 1, ncol
          if (boti(i) == 0) then
             ! Detect if we are outside the maximum range (where z = 20 km).
             if (zm(i,k) >= 20000._r8) then
                boti(i) = k
                topi(i) = k
             else
                ! First spot where heating rate is positive.
                if (netdt(i,k) > 0.0_r8) boti(i) = k
             end if
          else if (topi(i) == 0) then
             ! Detect if we are outside the maximum range (z = 20 km).
             if (zm(i,k) >= 20000._r8) then
                topi(i) = k
             else
                ! First spot where heating rate is no longer positive.
                if (.not. (netdt(i,k) > 0.0_r8)) topi(i) = k
             end if
          end if
       end do
       ! When all done, exit.
       if (all(topi /= 0)) exit
    end do
  end if
  ! Heating depth in m.  (top-bottom altitudes)
  hdepth = [ ( (zm(i,topi(i))-zm(i,boti(i))), i = 1, ncol ) ]
  hd_idx = index_of_nearest(hdepth, desc%hd)

  ! hd_idx=0 signals that a heating depth is too shallow, i.e. that it is
  ! either not big enough for the lowest table entry, or it is below the
  ! minimum allowed for this convection type.
  ! Values above the max in the table still get the highest value, though.

  where (hdepth < max(desc%min_hdepth, desc%hd(1))) hd_idx = 0

  ! Maximum heating rate.
  do k = minval(topi), maxval(boti)
     where (k >= topi .and. k <= boti)
        q0 = max(q0, netdt(:,k))
     end where
  end do

  ! Multiply by conversion factor
  ! (now 20* larger than what Zhang McFarlane said as they try to describe heating over 100km grid cell)
  q0 = q0 * CF
  qj = gravit/rair*q0 ! unit conversion to m/s3

  !-------------------------------------------------
  ! CS1 and CS should be equal in current implemen-
  ! tation.
  !-------------------------------------------------
  CS1 = sqrt( usteer**2._r8 + vsteer**2._r8 )
  CS = CS1  !*xv_steer + CS1*yv_steer

  ! -----------------------------------------------------------
  ! Calculate winds in reference frame of wave (uwavef,vwavef).
  ! This is like "(U-c)" in GW literature, where U and c are in
  ! ground-based speeds in a plane perpendicular to wave fronts.
  !------------------------------------------------------------
  do i=1,ncol
     udiff(i) = u(i,topi(i)) - usteer(i)
     vdiff(i) = v(i,topi(i)) - vsteer(i)
     do k=1,pver
        uwavef(i, k ) = u(i, k ) - usteer(i)
        vwavef(i, k ) = v(i, k ) - vsteer(i)
     end do
  end do
  !----------------------------------------------------------
  ! Wave relative wind at source level. This determines
  ! orientation of wave in the XY plane, and therefore the
  ! direction in which force from dissipating GW will be
  ! applied.
  !----------------------------------------------------------
  do i=1,ncol
     udiff(i) = uwavef( i, topi(i) )
     vdiff(i) = vwavef( i, topi(i) )
  end do
  !-----------------------------------------------------------
  ! Unit vector components (xv,yv) in direction of wavevector
  ! i.e., in which force will be applied
  !-----------------------------------------------------------
  call get_unit_vector(udiff , vdiff , xv, yv, ubisrc )
#if 0
  call outfld('UCELL_MOVMTN', usteer, ncol, lchnk)
  call outfld('VCELL_MOVMTN', vsteer, ncol, lchnk)
  call outfld('CS_MOVMTN', CS, ncol, lchnk)
  call outfld('STEER_LEVEL_MOVMTN',steer_level, ncol, lchnk )
  call outfld('XPWP_SRC_MOVMTN', xpwp_src , ncol, lchnk )
#endif
  !----------------------------------------------------------
  ! Project the local wave relative wind at midpoints onto the
  !  direction of the wavevector.
  !----------------------------------------------------------
  do k = 1, pver
     ubm(:,k) = dot_2d(uwavef(:,k), vwavef(:,k), xv, yv)
  end do
  ! Source level on-crest wind
  do i=1,ncol
     ubmsrc(i) = ubm(i,topi(i))
  end do

  !---------------------------------------------------------------
  ! adjust everything so that source level wave relative on-crest
  ! wind is always positive. Also adjust sign of unit vector
  ! components xv,yv if needed.
  !--------------------------------------------------------------
  do k=1,pver
     do i=1,ncol
        ubm(i,k) = sign( 1._r8 , ubmsrc(i) )* ubm(i,k)
     end do
  end do
  !
  do i=1,ncol
     xv(i) = sign( 1._r8 , ubmsrc(i) ) * xv(i)
     yv(i) = sign( 1._r8 , ubmsrc(i) ) * yv(i)
  end do



  ! Compute the interface wind projection by averaging the midpoint winds. (both same wind profile,
  ! just at different points of the grid)

  ! Use the top level wind at the top interface.
  ubi(:,1) = ubm(:,1)
  ubi(:,2:pver) = midpoint_interp(ubm)

  !-----------------------------------------------------------------------
  ! determine wind for lookup table
  ! need wind speed at the top of the convecitve cell and at the steering level
  uh = 0._r8
  do i=1,ncol
     ut(i) = ubm(i,topi(i))
     uh(i) = ut(i) - CS(i) ! wind at top in the frame moving with the cell
  end do

  !------------------------------------------------
  ! Set phase speeds to be used in gw_drag_prof.
  ! Since moving mountain winds have already been
  ! made relative to steering level this should be zero,
  ! but true ground based vector phase velocity is
  ! =(usteer,vsteer)
  !-------------------------------------------------
  c(:,0) = 0._r8

  !-----------------------------------------------------------------------
  ! Gravity wave sources
  !-----------------------------------------------------------------------
  ! Start loop over all columns.
  !-----------------------------------------------------------------------
  do i=1,ncol

     !---------------------------------------------------------------------
     ! Look up spectrum only if the heating depth is large enough, else leave
     ! tau = 0.
     !---------------------------------------------------------------------
     if (.not. use_gw_movmtn_pbl) then
        if (hd_idx(i) > 0) then
           !------------------------------------------------------------------
           ! Look up the spectrum using depth and uh.
           !------------------------------------------------------------------
           !hdmm_idx = index_of_nearest(hdepth, desc%hd)
           uhmm_idx = index_of_nearest(uh, desc%uh)
           taumm(i) = abs(desc%mfcc(uhmm_idx(i),hd_idx(i),0))
           taumm(i) = taumm(i)*qj(i)*qj(i)/AL/1000._r8
           ! assign sign to MF based on the ground based phase speed, ground based phase speed = CS
           taumm(i) = -1._r8*sign(taumm(i),CS(i))
           !find the right phase speed bin
           c0(i,:) = CS(i)
           c_idx(i,:) = index_of_nearest(c0(i,:),c(i,:))

           !input tau to top +1 level, interface level just below top of heating, remember it's in pressure
           ! everything is upside down (source level of GWs, level where GWs are launched)
           tau(i,c_idx(i,:),topi(i):topi(i)+1) = taumm(i)

        end if ! heating depth above min and not at the pole
     else
        !tau(i,0,topi(i):pver+1 ) = xpwp_src(i) ! 0.1_r8/10000._r8
        !  ---- This is what is actually needed by gw_drag_prof.
        !  ---- Probably need to think about safety bounds for topi.
        tau(i,0,topi(i)+1 ) = xpwp_src(i) 
     endif

  enddo
  !-----------------------------------------------------------------------
  ! End loop over all columns.
  !-----------------------------------------------------------------------


  write(*,*) " range topi       " , minval( topi ) , maxval(topi )
  write(*,*) " range xpwp_src   " , minval( xpwp_src ) , maxval(xpwp_src )
  write(*,*) " range tau        " , minval( tau )  , maxval(tau )

  
  ! Output the source level.
  src_level = topi
  tend_level = topi


end subroutine gw_movmtn_src

! Short routine to get the indices of a set of values rounded to their
! nearest points on a grid.
pure function index_of_nearest(x, grid) result(idx)
  real(r8), intent(in) :: x(:)
  real(r8), intent(in) :: grid(:)

  integer :: idx(size(x))

  real(r8) :: interfaces(size(grid)-1)
  integer :: i, n

  n = size(grid)
  interfaces = (grid(:n-1) + grid(2:))/2._r8

  idx = 1
  do i = 1, n-1
     where (x > interfaces(i)) idx = i + 1
  end do

end function index_of_nearest



! -------------------------------------------------------------------------
! Centroid-based steering/launch level determination for gw_movmtn.F90
!
! Intended insertion point: after index_of_nearest() and before
! shcu_flux_src(), inside module gw_movmtn. Both subroutines are module-
! private, matching the existing shcu_flux_src / vorticity_flux_src /
! index_of_nearest helpers (none of which are in the module's public list).
! -------------------------------------------------------------------------

subroutine weighted_centroid(w, z, ncol, pver, z_min, z_max, z_centroid, k_centroid)
  !------------------------------------------------------------------------
  ! Per-column height centroid of a positive-definite weight profile:
  !
  !     z_centroid = integral( z*w, dz ) / integral( w, dz )
  !
  ! restricted to z_min <= z <= z_max. Pass z_min = -huge(1._r8) and/or
  ! z_max = huge(1._r8) to disable either bound. Native model-level
  ! ordering is used directly (no resorting) -- the centroid ratio is
  ! unaffected by the integration direction since both the numerator
  ! and denominator pick up the same sign from dz.
  !------------------------------------------------------------------------
  integer,  intent(in)  :: ncol, pver
  real(r8), intent(in)  :: w(ncol,pver)
  real(r8), intent(in)  :: z(ncol,pver)
  real(r8), intent(in)  :: z_min, z_max

  real(r8), intent(out) :: z_centroid(ncol)
  integer,  intent(out) :: k_centroid(ncol)

  real(r8) :: wi(pver), zi(pver)
  real(r8) :: num, denom
  integer  :: i, k

  do i = 1, ncol
     zi = z(i,:)
     wi = w(i,:)

     where (zi < z_min .or. zi > z_max) wi = 0._r8

     num   = 0._r8
     denom = 0._r8
     do k = 1, pver-1
        num   = num   + 0.5_r8*(zi(k)*wi(k) + zi(k+1)*wi(k+1)) * (zi(k+1)-zi(k))
        denom = denom + 0.5_r8*(      wi(k) +       wi(k+1)) * (zi(k+1)-zi(k))
     end do

     if (denom /= 0._r8) then
        z_centroid(i) = num/denom
        k_centroid(i) = minloc( abs(zi - z_centroid(i)), dim=1 )
     else
        z_centroid(i) = -1._r8 ! -huge(1._r8) Any negative => no weight in [z_min,z_max]
        k_centroid(i) = -1
     end if
  end do

end subroutine weighted_centroid


!==========================================================================

subroutine vorticity_centroid_levels(vorticity, zm, ncol, pver, &
     z_min_pbl, z_max_pbl, &
     steering_level, launch_level, &
     z_steer, z_launch)
  !------------------------------------------------------------------------
  ! Steering level: height centroid of abs(vorticity), excluding the PBL
  !                 (z < z_min_pbl).
  ! Launch level:   height centroid of abs(vorticity) restricted to levels
  !                 above the steering level (the "top half" of the
  !                 profile). Replaces a fixed steering_level offset
  !                 (e.g. pverx-20) with a profile-derived diagnostic.
  !------------------------------------------------------------------------
  integer,  intent(in)  :: ncol, pver
  real(r8), intent(in)  :: vorticity(ncol,pver)
  real(r8), intent(in)  :: zm(ncol,pver) ! Vertical coordinate, could be P(Pa) or z(m),
                                         ! but you better keep track and be consistent
  real(r8), intent(in)  :: z_min_pbl, z_max_pbl

  integer, intent(out) :: steering_level(ncol)
  integer, intent(out) :: launch_level(ncol)
  real(r8), intent(out) :: z_steer(ncol)
  real(r8), intent(out) :: z_launch(ncol)

  real(r8) :: absvort(ncol,pver), w_top(ncol,pver)
  real(r8) :: z_cent(ncol), z_top(ncol)
  integer  :: i

  absvort = abs(vorticity)

  ! --- first centroid: full column above the PBL ---
  call weighted_centroid(absvort, zm, ncol, pver, z_min_pbl, z_max_pbl, &
                          z_cent, steering_level)

  ! --- restrict to levels above the steering level (smaller k = higher up) ---
  w_top = absvort
  do i = 1, ncol
     if (steering_level(i) > 0) then
        w_top(i, steering_level(i):pver) = 0._r8
     else
        w_top(i,:) = 0._r8   ! propagate "no signal" from the first pass
     end if
  end do

  ! --- second centroid: "top half" of the profile ---
  call weighted_centroid(w_top, zm, ncol, pver, -huge(1._r8), huge(1._r8), &
                          z_top, launch_level)

  z_steer = z_cent
  z_launch = z_top
end subroutine vorticity_centroid_levels


!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine shcu_flux_src (xpwp_shcu , ncol, pverx, alpha_gw_movmtn, xpwp_src, steering_level, launch_level )
  integer, intent(in) :: ncol,pverx
  real(r8), intent(in) :: xpwp_shcu (ncol,pverx)
  real(r8), intent(in) :: alpha_gw_movmtn

  real(r8), intent(out) :: xpwp_src(ncol)
  integer,  intent(out) :: steering_level(ncol), launch_level(ncol)

  integer :: k, nlayers

  steering_level(:ncol) = (pverx-1) - 5 !++ tuning test 12/30/24
  launch_level(:ncol)   = steering_level -10 !++ tuning test 01/05/25

  !-----------------------------------
  ! Simple average over layers.
  ! Probably can do better
  !-----------------------------------
  nlayers=5
  xpwp_src(:) =0._r8
  do k = 0, nlayers-1
     xpwp_src(:) = xpwp_src(:) + xpwp_shcu(:,pverx-k)
  end do
  xpwp_src(:) = alpha_gw_movmtn * xpwp_src(:)/(1.0_r8*nlayers)

end subroutine shcu_flux_src

!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine vorticity_flux_src (vorticity , ncol, pverx, alpha_gw_movmtn, vort_src, steering_level, launch_level )
  integer, intent(in) :: ncol,pverx
  real(r8), intent(in) :: vorticity (ncol,pverx)
  real(r8), intent(in) :: alpha_gw_movmtn

  real(r8), intent(out) :: vort_src(ncol)
  integer,  intent(out) :: steering_level(ncol), launch_level(ncol)

  real(r8) :: scale_factor
  integer  :: k, nlayers

  steering_level(:ncol) = pverx - 20
  launch_level(:ncol)   = steering_level -10

  scale_factor   = 1.e4_r8 ! scales vorticity amp to u'w' in CLUBB
  !-----------------------------------
  ! Simple average over layers.
  ! Probably can do better
  !-----------------------------------
  nlayers=10
  vort_src(:) =0._r8
  do k = 0, nlayers-1
     vort_src(:) = vort_src(:) + scale_factor * abs( vorticity(:,pverx-k) )
  end do
  vort_src(:) = alpha_gw_movmtn * vort_src(:)/nlayers

end subroutine vorticity_flux_src

#if 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine tilt_dyn_src(tilt, u, v, pmid, delp, ncol, pver, alpha_gw_movmtn, &
     xpwp_src, steering_level, launch_level, p_steer, p_launch, &
     usteer, vsteer)
  !------------------------------------------------------------------------
  ! Flow-dependent GW source using the tilt field.
  !
  ! 1. Centroid of |tilt| in pressure space gives the steering level
  !    and launch level.
  ! 2. Source flux = pressure-weighted mean tilt between launch and
  !    steering levels, scaled by alpha_gw_movmtn and scale_factor.
  ! 3. Sentinel handling: if the centroid search fails for a column
  !    (steering_level or launch_level returns -1), xpwp_src is zeroed
  !    and levels are set to safe fallback values (Steer=2, Launch=1)
  !    so downstream code (heating depth, wind projection) is never
  !    handed an out-of-bounds index.
  !
  ! usteer, vsteer are returned here rather than extracted in the driver
  ! because the sentinel fallback modifies steering_level, and the driver
  ! should see the already-corrected index.
  !------------------------------------------------------------------------
  integer,  intent(in)  :: ncol, pver
  real(r8), intent(in)  :: tilt(ncol,pver)
  real(r8), intent(in)  :: u(ncol,pver), v(ncol,pver)
  real(r8), intent(in)  :: pmid(ncol,pver)
  real(r8), intent(in)  :: delp(ncol,pver)
  real(r8), intent(in)  :: alpha_gw_movmtn

  real(r8), intent(out) :: xpwp_src(ncol)
  integer,  intent(out) :: steering_level(ncol), launch_level(ncol)
  real(r8), intent(out) :: p_steer(ncol), p_launch(ncol)
  real(r8), intent(out) :: usteer(ncol), vsteer(ncol)

  real(r8), parameter :: scale_factor    = 1.e6_r8
  real(r8), parameter :: p_min_centroid  = 0._r8
  real(r8), parameter :: p_max_centroid  = 80000._r8

  real(r8) :: z_steer(ncol), z_launch(ncol)
  integer  :: i

  !--- Centroid-based steering and launch levels --------------------------
  call vorticity_centroid_levels(tilt, pmid, ncol, pver, &
       p_min_centroid, p_max_centroid, &
       steering_level, launch_level, &
       z_steer, z_launch)

  !--- Pressure-weighted mean tilt; sentinel handling --------------------
  xpwp_src = 0._r8
  do i = 1, ncol
     if (steering_level(i) >= 2 .and. launch_level(i) >= 2 .and. &
          steering_level(i) > launch_level(i)) then
        xpwp_src(i) = &
             sum(tilt(i, launch_level(i):steering_level(i)) &
             *   delp(i, launch_level(i):steering_level(i))) &
             / sum(delp(i, launch_level(i):steering_level(i)))
        p_steer(i)  = pmid(i, steering_level(i))
        p_launch(i) = pmid(i, launch_level(i))
        usteer(i)   = u(i, steering_level(i))
        vsteer(i)   = v(i, steering_level(i))
     else
        ! Centroid search failed: zero source, fall back to safe indices.
        xpwp_src(i)       = 0._r8
        steering_level(i) = 2
        launch_level(i)   = 1
        p_steer(i)        = pmid(i, 2)
        p_launch(i)       = pmid(i, 1)
        usteer(i)         = u(i, 2)
        vsteer(i)         = v(i, 2)
     end if
  end do

  xpwp_src = alpha_gw_movmtn * scale_factor * xpwp_src

end subroutine tilt_dyn_src
#endif


!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine compute_tilt(u, v, zeta, zm, ncol, pver, tilt)
  !------------------------------------------------------------------------
  ! Compute the tilting term magnitude:
  !
  !   tilt(i,k) = sqrt( (du/dz * zeta)^2 + (dv/dz * zeta)^2 )
  !             = |zeta| * sqrt( (du/dz)^2 + (dv/dz)^2 )
  !
  ! where du/dz and dv/dz are vertical wind shears computed by finite
  ! differences on the native (irregular) zm grid.
  !
  ! CAM level ordering: k=1 is TOA, k=pver is surface.
  ! Therefore zm(i,k) > zm(i,k+1), i.e. altitude decreases with k.
  ! Centred differences are used in the interior; one-sided differences
  ! at the top (k=1) and bottom (k=pver) boundaries.
  !
  ! Arguments
  ! ----------
  ! u, v    : midpoint zonal/meridional winds (ncol, pver)  [m/s]
  ! zeta    : relative vorticity              (ncol, pver)  [1/s]
  ! zm      : midpoint altitudes              (ncol, pver)  [m]
  ! tilt    : tilting term magnitude          (ncol, pver)  [1/s * 1/s / m]
  !           = [s^-2 m^-1]  (same units as du/dz * zeta)
  !------------------------------------------------------------------------
  use gw_utils, only: r8

  implicit none

  integer,  intent(in)  :: ncol, pver
  real(r8), intent(in)  :: u(ncol,pver)
  real(r8), intent(in)  :: v(ncol,pver)
  real(r8), intent(in)  :: zeta(ncol,pver)
  real(r8), intent(in)  :: zm(ncol,pver)
  real(r8), intent(out) :: tilt(ncol,pver)

  real(r8) :: uz, vz, dz
  integer  :: i, k

  do i = 1, ncol

     ! --- top boundary: one-sided difference (k=1, no k-1 above) ---
     dz        = zm(i,1) - zm(i,2)          ! positive: z(k=1) > z(k=2)
     uz        = (u(i,1) - u(i,2)) / dz
     vz        = (v(i,1) - v(i,2)) / dz
     tilt(i,1) = sqrt( (uz*zeta(i,1))**2 + (vz*zeta(i,1))**2 )

     ! --- interior: centred differences ---
     do k = 2, pver-1
        dz        = zm(i,k-1) - zm(i,k+1)  ! spans two layers
        uz        = (u(i,k-1) - u(i,k+1)) / dz
        vz        = (v(i,k-1) - v(i,k+1)) / dz
        tilt(i,k) = sqrt( (uz*zeta(i,k))**2 + (vz*zeta(i,k))**2 )
     end do

     ! --- bottom boundary: one-sided difference (k=pver, no k+1 below) ---
     dz           = zm(i,pver-1) - zm(i,pver)
     uz           = (u(i,pver-1) - u(i,pver)) / dz
     vz           = (v(i,pver-1) - v(i,pver)) / dz
     tilt(i,pver) = sqrt( (uz*zeta(i,pver))**2 + (vz*zeta(i,pver))**2 )

  end do

end subroutine compute_tilt

end module gw_movmtn
